apiVersion: v1
kind: Secret
metadata:
  name: teacher-service-secret
  namespace: edu
type: Opaque
stringData:
  DATABASE_URL: "postgres://edu:edu-secret-change-me@postgres.edu.svc.cluster.local:5432/edu?options=-c%20search_path%3Dteacher"
  JWT_SECRET: "your-jwt-secret-change-in-production"
